platzi_awards/platzi_awards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

platzi_awards/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
        path('', views.IndexView.as_view(), name='q_index'),
        path('<int:pk>/', views.DetailView.as_view(), name='q_info'),
        path('<int:pk>/count', views.ResultsView.as_view(), name='q_count'),
        path('<int:question_id>/vote', views.question_vote, name='q_vote'),
        ]

platzi_awards/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question (models.Model):
    question_str = models.CharField(max_length=256)
    publication_date = models.DateTimeField('date published')

    def __str__ (self):
        return str(self.question_str)

    def was_published_recently (self):
        return timezone.now() >= self.publication_date >= timezone.now() - datetime.timedelta(days=1)

class Choice (models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_str = models.CharField(max_length=128)
    choice_votes = models.IntegerField(default=0)

    def __str__ (self):
        return str(self.choice_str)

platzi_awards/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils import timezone

from .models import Question, Choice


# Create your views here.

# def index (request):
    # latest_question_list = Question.objects.all()
    # return render(request, 'polls/index.html', {
        # 'latest_question_list': latest_question_list
        # })

class IndexView (generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset (self):
        """ Return the List of Published Questions """
        return Question.objects.filter(publication_date__lte=timezone.now()).order_by("-publication_date")

class DetailView (generic.DetailView):
    model = Question
    template_name = 'polls/question_info.html'

    def get_queryset(self):
        return Question.objects.filter(publication_date__lte=timezone.now())

class ResultsView (DetailView):
    template_name = 'polls/question_count.html'


# def question_info (request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/question_info.html', {
        # 'question': question
        # })



# def question_count (request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/question_count.html', {
        # 'question': question
        # })


def question_vote (request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExists):
        return render(request, 'polls/question_info.html', {
            'question': question,
            'error_message': 'Question\'s Choice not Selected'
            })

    selected_choice.choice_votes += 1
    selected_choice.save()

    return HttpResponseRedirect(reverse('polls:q_count', args=[question.id]))

platzi_awards/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:q_info' question.id %}">{{ question.question_str }}</a></li>
        {% endfor %} 
    </ul>
    {% else %}
    <p>No Polls are Available</p>
{% endif %}

platzi_awards/polls/templates/polls/question_count.html
<h1>{{ question.question_str }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_str }} : {{ choice.choice_votes }} vote{{ choice.choice_votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:q_info' question.id %}">Vote Again</a>

platzi_awards/polls/templates/polls/question_info.html
<form action="{% url 'polls:q_vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_str }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
           <input 
            type="radio" 
            name="choice" 
            id="choice{{ forloop.counter }}" 
            value="{{ choice.id }}">
           <label for="choice{{ forloop.counter }}">
                {{ choice.choice_str }}
           </label>
           <br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="votar">
</form>

{#<h1>{{ question.question_str }}</h1>#}
{#<ul>#}
    {#{% for choice in question.choice_set.all %}#}
        {#<li>{{ choice.choice_str }}</li>#}
    {#{% endfor %}#}
{#</ul>#}